---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:C:/Users/user/IdeaProjects/OrderService/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1

management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true